services:
  php:
    build: .
    environment:
      APP_ENV: '${APP_ENV:-dev}'
      COMPOSER_HOME: /home/docker/.composer
#      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_MODE: 'debug,coverage'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: 'serverName=slub-cli'
    user: 'www-data'
    volumes:
      - ./:/srv/slub
    working_dir: /srv/slub
    networks:
      - 'slub'

  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'slub'
      MYSQL_DATABASE: 'slub'
      MYSQL_PASSWORD: 'slub'
    ports:
      - '${DOCKER_PORT_MYSQL:-33006}:3306'
    networks:
      - 'slub'

networks:
  slub:
