version: '3.5'

services:
    php:
        build: .
        environment:
            APP_ENV: '${APP_ENV:-dev}'
            COMPOSER_HOME: /home/docker/.composer
        user: 'www-data'
        volumes:
            - ./:/srv/slub
        working_dir: /srv/slub
        networks:
            - 'slub'

    mysql:
        image: 'mysql:8.0.26'
        command: '--default-authentication-plugin=mysql_native_password'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'slub'
            MYSQL_DATABASE: 'slub'
            MYSQL_PASSWORD: 'slub'
        ports:
            - '${DOCKER_PORT_MYSQL:-33006}:3306'
        networks:
            - 'slub'



networks:
    slub:
